# Site settings
title: 阿志的个人博客
url: "localhost"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  记录本人的点点滴滴.

# Your information
email: zhenglizhi56@gmail.com
author: jackzlz
avatar: "//s.gravatar.com/avatar/089daafa0d097e999f54fcfd94b74832?s=135"
profile: coding my life.
twitter_username: jackzlz
github_username:  jackzlz

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
duoshuo_shortname: jackzlz  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown
excerpt_separator: <!--more-->

kramdown:
  input: GFM
  syntax_highlighter: rouge
