markdown: kramdown
safe: false
excerpt_separator: <!--more-->

exclude:
  - README.md

name: 阿志
host: localhost
desc: 阿志的个人博客

custom:
    category:
        default: Default Category
        another: Another Category
        zikao: 自考
        qishe: 骑摄
        tech: 技术
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

      - name: zikao
        title: 自考

      - name: qishe
        title: 骑摄

      - name: tech
        title: 技术

    scrollingLoadCount: 0                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 阿志
        email: jackzlz@126.com
        #disqus: your-disqus-short-name              # Disqus缩略标识
        #gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        #github: your-github-account                 # GitHub账号
        gravatar: 089daafa0d097e999f54fcfd94b74832  # Gravatar头像标识

    #disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    #gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
